name: chip8
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Jonah Williams <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
transformers:
  - dart_to_js_script_rewriter